server:
  port: 9000
spring:
  data.redis:
    database: 0
    host: 127.0.0.1
    port: 12040
    password: 123456
    lettuce:
      pool:
        max-active: 10
        max-idle: 5
        max-wait: 10000
        min-idle: 3
    timeout: 50000
# 日志打印级别
logging:
  level:
    web: debug
    com.authorization.gateway: debug
    com.alibaba.nacos.client.config.impl.ClientWorker: warn
    com.authorization.utils.listener.ApplicationEvenListener: warn